name: Daily Menu Scraper

on:
  schedule:
    - cron: '1 5 * * *' # 12:01 AM EST
  workflow_dispatch:

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./server 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper Script
        env:
          SUPABASE_PROJECT_URL: ${{ secrets.SUPABASE_PROJECT_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_ANON_API_KEY: ${{ secrets.SUPABASE_ANON_API_KEY }}
          PYTHONPATH: . 
        run: |
          python -m app.daily_scrape